# Generated by Django 4.2.6 on 2023-10-23 05:24

import animais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[animais.models.Animal.validate_nome])),
                ('especie', models.CharField(choices=[('c', 'cachorro'), ('g', 'gato'), ('o', 'outro')], max_length=8, verbose_name='espécie')),
                ('sexo', models.CharField(choices=[('m', 'macho'), ('f', 'fêmea')], max_length=5)),
                ('imagem', models.URLField()),
                ('adicionado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
