# Generated by Django 4.2.6 on 2023-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('especie', models.CharField(choices=[('c', 'Cachorro'), ('g', 'Gato')], max_length=8)),
                ('sexo', models.CharField(choices=[('m', 'Macho'), ('f', 'Fêmea')], max_length=5)),
                ('adicionado_em', models.DateTimeField(verbose_name='data de cadastro do animal')),
            ],
        ),
    ]
