# Generated by Django 4.2.6 on 2023-10-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('c', 'cachorro'), ('g', 'gato')], max_length=8),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('m', 'macho'), ('f', 'fêmea')], max_length=5),
        ),
    ]
