# Generated by Django 4.2.6 on 2023-10-22 17:30

import animais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_alter_animal_especie_alter_animal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animal_images/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='adicionado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('c', 'cachorro'), ('g', 'gato'), ('o', 'outro')], max_length=8, verbose_name='espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, validators=[animais.models.Animal.validate_nome]),
        ),
    ]
