# Generated by Django 4.2.6 on 2023-10-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_animal_imagem_alter_animal_adicionado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
